version: "3.9"

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-a*yc@fvxfk!!)%xgs%m041^+xfjflzyc8$$_+mq7db2o+zy*0pp"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:15.2
    volumes:
      - pgdata:/var/lib/postgresql/data/
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 2s
      retries: 10

volumes:
  pgdata:
